blog/urls.py
from django.urls import path 
from .views import *

app_name = 'blog'

urlpatterns = [
    path('about/', about_page_view, name='blog-about'), 
    path('policy/', privacy_policy_view, name='blog-policy'),
    path('terms/', terms_conditions_view, name='blog-term'),

]

stories/urls.py
from django.urls import path 
from .views import *

app_name = 'story'

urlpatterns = [
    path('', story_list_view, name='story-list'), 
    path('story/detail/<str:ids>/',story_detail_view, name='story-detail'),
    path('search/story/', search_story_view, name='story-search'),

]

survivorlink/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _


urlpatterns = [
    path(_('admin/'), admin.site.urls),
    
]

urlpatterns += i18n_patterns (
    path('blog/', include('blog.urls', namespace='blog')),
    path('', include('stories.urls', namespace='story')),
    path('tips/', include('tips.urls', namespace='tips')),
)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tips/urls.py
from django.urls import path 
from .views import *

app_name = 'tips'

urlpatterns = [
    path('', tip_list_view, name='tip-list'), 
    path('detail/<str:ids>/', tip_detail_view, name='tip-detail'),

]

blog/models.py
from django.db import models

# Create your models here.
class About(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()

    class Meta:
        ordering = ['-title',]

    def __str__(self):
        return self.title 


class CustomerCall(models.Model):
    mobile = models.CharField(max_length=50, blank=True, help_text="Optional field")

    class Meta:
        verbose_name_plural = 'Customer Calls'

    def __str__(self):
        return self.mobile


class CustomerEmail(models.Model):
    email = models.CharField(max_length=100, blank=True, help_text="Optional field")

    class Meta:
        verbose_name_plural = 'Customer Emails'

    def __str__(self):
        return self.email

stories/models.py
from django.db import models
from django.urls import reverse 
from django.contrib.auth.models import User 
from django.dispatch import receiver  


# Create your models here. 
class Story(models.Model):
    publisher = models.ForeignKey(User, on_delete=models.CASCADE, help_text="Who is publishing the story.")
    title = models.CharField(max_length=300, help_text="Title of your story.")
    content = models.TextField(blank=True, help_text="Describe the story. This field is optional.")
    is_available = models.BooleanField(default=True, help_text="Is this for everyone.")
    author = models.CharField(max_length=100, blank=True, help_text="Who is the owner of the story. This field is optional.")
    date = models.DateTimeField(auto_now_add=True) 
    video_url = models.CharField(max_length=1000, blank=True)
    # thumbnail = models.CharField(max_length=1000, blank=True)


    class Meta:
        ordering = ['-date',] 
        verbose_name_plural = 'Stories'

    def __str__(self):
        return f"{self.publisher} - {self.title} - {self.date}" 
    
    def get_absolute_url(self):
        return reverse('story:story-detail', kwargs={'pk': self.pk})

tips/models.py
from django.db import models
from django.urls import reverse 
from django.contrib.auth.models import User 
from django.dispatch import receiver  


# Create your models here. 
class Tip(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, help_text="The author's name.")
    title = models.CharField(max_length=300, help_text="What is the title?.")
    content = models.TextField(help_text="Write the content.")
    is_available = models.BooleanField(default=True, help_text="Is this for everyone.")
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-date',] 
        verbose_name_plural = 'Tips'

    def __str__(self):
        return f"{self.author} - {self.title} - {self.date}" 
    
    def get_absolute_url(self):
        return reverse('tips:tip-detail', kwargs={'pk': self.pk})

blog/views.py
from django.shortcuts import render
from .models import *
from django.utils.translation import gettext as _
from django.utils.translation import get_language, activate, gettext


# Create your views here.
def about_page_view(request):
    about_data = About.objects.all()
    call_data = CustomerCall.objects.all()
    email_data = CustomerEmail.objects.all()

    context = {
        'about_data':about_data,
        'call_data':call_data,
        'email_data':email_data,
    }
    return render(request, 'blog/about.html', context)


def privacy_policy_view(request):
    return render(request, 'blog/privacy_policy.html')


def terms_conditions_view(request):
    return render(request, 'blog/term_condition.html')

stories/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import User 
from django.db.models import Q 
from django.contrib import messages 
from django.views.generic import ListView, DetailView 
from .models import * 
from django.core.paginator import Paginator


# Create your views here.
def story_list_view(request):
    story_data = Story.objects.all()
    context = {
        'story_data':story_data
    }
    return render(request, 'stories/story_list.html', context)


def story_detail_view(request, ids):
    ids = get_object_or_404(Story, id=ids)
    context = {
        'ids':ids
    }
    return render(request, 'stories/story_detail.html', context)


def search_story_view(request):
    query = request.GET.get('q', None)
    if query == None or query == "":
        story_data = Story.objects.all()
    elif query is not None:
        story_data = Story.objects.filter(
            Q(publisher__username__icontains=query)|
            Q(publisher__email__icontains=query)|
            Q(title__icontains=query)|
            Q(content__icontains=query)|
            Q(author__icontains=query)|
            Q(date__icontains=query)).distinct()

    context = {
        'story_data':story_data
    }
    return render(request, 'stories/story_list.html', context)

tips/views.py
from django.shortcuts import render, get_object_or_404  
from django.views.generic import ListView, DetailView 
from .models import * 



# Create your views here.
def tip_list_view(request):
    tip_data = Tip.objects.all()
    context = {
        'tip_data':tip_data
    }
    return render(request, 'tips/tip_list.html', context)


def tip_detail_view(request, ids):
    ids = get_object_or_404(Tip, id=ids)
    context = {
        'ids':ids
    }
    return render(request, 'tips/tips_detail.html', context)

blog/templates/blog/about.html
{% extends 'blog/base.html' %}
{% load static %}
{% load crispy_forms_tags %} 
{% load i18n %}
{% block content %}

<div class="container">
    <div class="my-2">
        <a href="{% url 'story:story-list' %}" class="mdl-color-text--purple">
            <!-- {% trans "Home" %} &gt; {% trans "About" %} -->
            <i class="material-icons" role="presentation">home</i>
            &gt; {% trans "About" %} &gt;
        </a>
    </div>
    <div class="line mb-3"></div>

    <div class="row featurette mb-5">
        <div class="col-md-6 mb-3">
            <div class="container">
                {% for obj in about_data %}
                    <p class="txt-color h4">
                        {% blocktranslate with t=obj.title|capfirst %}{{t}}{% endblocktranslate %}
                    </p>
                    <p class="lead">
                        {% blocktranslate with c=obj.content|safe|capfirst|linebreaks %}{{c}}{% endblocktranslate %}
                    </p>
                {% endfor %}

                <div class="line"></div>
                <p class="txt-color h4">{% trans "Call us" %}</p>
                {% for obj in call_data %}
                    <p class="h5">{% trans "Phone" %}: {{obj.mobile}}</p>
                {% endfor %}

                <div class="line"></div>
                <p class="txt-color h4">{% trans "Write us" %}</p>
                {% for obj in email_data %}
                    <p class="h5">{% trans "Email" %}: {{obj.email}}</p>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-6 mb-3">
            <img src="{% static 'blog/assets/abt1.jpg' %}" class="detail-img img-effect bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto bg-light" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false">
        </div>
    </div>

</div>

{% endblock %}

blog/templates/blog/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html>
<head>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="IE=edge">

<meta name="description" content="Sharing the true lives stories to society to fight HTPs.">
<meta name="author" content="Survivors Link">

<title>Umiza</title>

<link rel="icon" type="image/x-icon" class="rounded-circle" href="{% static 'blog/assets/logo.ico' %}" />

{% if title %}
    <title>Umiza - {{ title }}</title>
{% else %}
    <title>Umiza</title>
{% endif %} 


<!-- Material Design Lite -->
<script src="{% static 'blog/mdl/material.min.js' %}"></script>
<script src="{% static 'blog/mdl/material.js' %}"></script>

<link rel="stylesheet" href="{% static 'blog/mdl/material.min.css' %}">
<link rel="stylesheet" href="{% static 'blog/mdl/material.css' %}">

<link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.purple-blue.min.css" />
<!-- Material Design icon font -->
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

<link rel="stylesheet" href="{% static 'blog/bootstrap/css/bootstrap.min.css' %}">
<script src="{% static 'blog/bootstrap/js/jquery-3.2.1.slim.min.js' %}"></script>
<script src="{% static 'blog/bootstrap/js/popper.min.js' %}"></script>
<script src="{% static 'blog/bootstrap/js/bootstrap.min.js' %}"></script>


<style type="text/css">
    div, a, li, p, h1, h2, h3, h4, h5, h6{
        font-family: 'Poppins', sans-serif;
        font-size: 1.02em;
        font-weight: 300;
        line-height: 1.7em;
        color: grey;
    }

    .bg-color{
        background-color: #60327c !important;
        color: white;
    }

    .line {
        width: 100%;
        height: 1px;
        border-bottom: 1px dashed #ddd;
        margin: 10px 0;
    }

    .txt-color{
        color: #60327c !important; 
    }

    .demo-layout-waterfall .mdl-layout__header-row .mdl-navigation__link:last-of-type  {
        padding-right: 0;
        text-decoration: none !important;
    }

    a {
        text-decoration: none !important;
    }

    .detail-img {
        width: 100%;
        height: 380px;
        border-radius: 0.2rem;
    }

    .grid-max-width {
        max-width: 1200px;
        margin: auto;
    }

    .img-effect{
        border-radius: 4px;
        background: #fff;
        box-shadow: 0 6px 10px rgba(0,0,0,.08), 0 0 6px rgba(0,0,0,.05);
        transition: .3s transform cubic-bezier(.155,1.105,.295,1.12),.3s box-shadow,.3s -webkit-transform cubic-bezier(.155,1.105,.295,1.12);
        padding: 2px 2px 2px 2px;
        cursor: pointer;
    }

    .img-effect:hover{
        transform: scale(1.02);
        box-shadow: 0 10px 20px rgba(0,0,0,.12), 0 4px 8px rgba(0,0,0,.06);
    }

</style>

</head>
<body>
    <!-- Uses a header that scrolls with the text, rather than staying
      locked at the top -->
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
        <header class="mdl-layout__header bg-color">
            <div class="mdl-layout__header-row">
                <!-- Title -->
                <span class="mdl-layout-title">
                    <a href="{% url 'story:story-list' %}" class="mdl-color-text--white">
                        <img class="mr-2 rounded-circle" height="35" width="35" src="{% static 'blog/assets/logo.ico' %}">
                        Umiza
                    </a>
                </span>

                <!-- Add spacer, to align navigation to the right -->
                <div class="mdl-layout-spacer"></div>
                <!-- Navigation -->
                <nav class="mdl-navigation mdl-layout--large-screen-only">
                    <a class="mdl-navigation__link" href="{% url 'story:story-list' %}">{% trans "Home" %}</a>
                    <a class="mdl-navigation__link" href="{% url 'tips:tip-list' %}">{% trans "Tips" %}</a>
                    <a class="mdl-navigation__link" href="{% url 'blog:blog-about' %}">{% trans "About" %}</a>
                </nav>
          
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--expandable mdl-textfield--floating-label mdl-textfield--align-right my-auto">
                    <form method="GET" action="{% url 'story:story-search' %}" class="d-flex">
                        <label class="mdl-button mdl-js-button mdl-button--icon mdl-color-text--white" for="fixed-header-drawer-exp">
                            <i class="material-icons">search</i>
                        </label>
                        <div class="mdl-textfield__expandable-holder">
                            <input class="mdl-textfield__input mdl-color-text--white q"  type="text" name="q" value="{{request.GET.q}}" id="fixed-header-drawer-exp">
                        </div>
                    </form>
                </div>
            </div>
        </header>
        <main class="mdl-layout__content bg-light">
            <a name="top"></a>
            <div class="page-content mx-auto">
                <!-- Your content goes here -->
                {% block  title %}{% endblock title %}


                <div class="mdl-grid grid-max-width mb-5">
                    {% block  content %}{% endblock %}
                </div>
            </div>


            <footer class="mdl-mini-footer mt-5">
                <div class="mdl-mini-footer__left-section">
                    <div class="mdl-logo">
                        <a href="{% url 'story:story-list' %}" class="mdl-color-text--white">
                            <img class="mr-2 rounded-circle" height="35" width="35" src="{% static 'blog/assets/logo.ico' %}">Umiza
                        </a>
                    </div>
                </div>
                <div class="mdl-mini-footer__right-section">
                    <ul class="mdl-mini-footer__link-list">
                        <li>
                            <a href="{% url 'blog:blog-about' %}" class="mdl-color-text--white">{% trans "About" %}</a>
                        </li>
                        <li>
                            <a href="{% url 'tips:tip-list' %}" class="mdl-color-text--white">{% trans "Tips" %}</a>
                        </li>
                        <li>
                            <a href="{% url 'blog:blog-term' %}" class="mdl-color-text--white">{% trans "Terms" %}</a>
                        </li>
                        <li>
                            <a href="{% url 'blog:blog-policy' %}" class="mdl-color-text--white">{% trans "Privacy Policy" %}</a>
                        </li>
                    </ul>
                </div>
            </footer>

        </main>
    </div>

</body>
</html>

blog/templates/blog/privacy_policy.html
{% extends 'blog/base.html' %}
{% load static %}
{% load i18n %}
{% block content %}

<div class="container">
    <div class="my-2">
        <a href="{% url 'story:story-list' %}" class="mdl-color-text--purple">
            <!-- {% trans "Home" %} &gt; {% trans "Privacy Policy" %} -->
            <i class="material-icons" role="presentation">home</i>
            &gt; {% trans "Privacy Policy" %} &gt;
        </a>
    </div>
    <div class="line mb-3"></div>

    <div class="mdl-cell mdl-cell--10-col mdl-cell--12-col-tablet mdl-cell--12-col-phone mdl-shadow--2dp mx-auto">
        <div class="container p-4">
            <center>
                <p class="h3">Coming Soon</p>
                <p class="h3 mdl-color-text--purple">Not available!</p>
            </center>
        </div>
    </div>

</div>


{% endblock %}

blog/templates/blog/term_condition.html
{% extends 'blog/base.html' %}
{% load static %}
{% load i18n %}
{% block content %}

<div class="container">
    <div class="my-2">
        <a href="{% url 'story:story-list' %}" class="mdl-color-text--purple">
            <!-- {% trans "Home" %} &gt; {% trans "Terms" %} -->
            <i class="material-icons" role="presentation">home</i>
            &gt; {% trans "Terms" %} &gt;
        </a>
    </div>
    <div class="line mb-3"></div>

    <div class="mdl-cell mdl-cell--10-col mdl-cell--12-col-tablet mdl-cell--12-col-phone mdl-shadow--2dp mx-auto">
        <div class="container p-4">
            <center>
                <p class="h3">Coming Soon</p>
                <p class="h3 mdl-color-text--purple">Not available!</p>
            </center>
        </div>
    </div>

</div>


{% endblock %}

stories/templates/stories/story_detail.html
{% extends 'blog/base.html' %}
{% load static %}
{% load i18n %} 
{% block content %}

<div class="container">
    <div class="my-2">
        <a href="{% url 'story:story-list' %}" class="mdl-color-text--purple">
            <i class="material-icons" role="presentation">home</i>
            &gt; {% trans "Details" %} &gt;
        </a>
    </div>
    <div class="line mb-3"></div>

    <div class="mdl-cell mdl-cell--10-col mdl-cell--12-col-tablet mdl-cell--12-col-phone mdl-shadow--2dp mx-auto">
        {% if ids.video_url != None %}
            <div class="mb-0">
                <!-- <video controls controlsList="nodownload" width="100%" poster="{% static 'blog/assets/abt0.jpg' %}">
                    <source src="{{ids.video_url.url}}" type="video/mp4">
                    Sorry, your browser doesn't support embedded videos.
                </video> -->
                <img src="{{ids.video_url}}" width="100%">
            </div>
        {% endif %}
        <div class="container p-4">
            <p class="txt-color h4">
                {% blocktranslate with t=ids.title|capfirst %}{{t}}{% endblocktranslate %}
            </p>
            {% if ids.author %}
                <p class="mdl-color-text--red-600 h6">
                    {% trans "Author" %}: {{ids.author|capfirst}}
                </p>
            {% endif %}
            <p class="lead">
                {% blocktranslate with c=ids.content|safe|capfirst|linebreaks %}{{c}}{% endblocktranslate %}
            </p>
            <p class="txt-color h5">
                {% trans "On" %} {% blocktranslate with dt=ids.date|date %}{{dt}}{% endblocktranslate %} | {% trans "By" %} {{ids.publisher|capfirst}}
            </p>

        </div>
    </div>

</div>


{% endblock %}

stories/templates/stories/story_list.html
{% extends 'blog/base.html' %}
{% load static %}
{% load crispy_forms_tags %} 
{% load i18n %}


{% block  title %}
<div class="jumbotron jumbotron-fluid mdl-typography--text-center px-3" style="background-color: #dfd7e5;">
    <h1 class="h1 mdl-color-text--purple-600">
        {% trans "Welcome To Our Site!" %}
    </h1>
    <p class="lead mx-auto">
        {% trans "Sharing the true lives stories to society to fight harmful traditional practices." %}
    </p>
    <p class="lead mx-auto">
        {% trans "Together we fight harmful traditional practices." %}
    </p>

    <!-- <div class="dropdown">
        <button class="btn btn-secondary btn-md dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-expanded="false">
            {% trans "Language" %}
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            {% get_current_language as LANGUAGE_CODE %}
            {% get_available_languages as LANGUAGES %}
            {% get_language_info_list for LANGUAGES as languages %}
            <li><h6 class="dropdown-header">Select Language</h6></li>
            {% for lang in languages %}
            <li>
                <a class="dropdown-item selected" href="/{{ lang.code }}/">
                    {{lang.name_local|capfirst}}
                </a>
            </li>
            {% endfor %}
        </ul>
    </div> -->


</div>
{% endblock title %}



{% block content %}

{% for obj in story_data %}
{% if obj.is_available == True %}
<div class="mdl-cell mdl-cell--4-col mdl-cell--4-col-tablet mdl-cell--4-col-phone mdl-shadow--2dp">
    <div class="container p-3">
        <p class="txt-color h4">
            {% blocktranslate with t=obj.title|capfirst|truncatechars:30 %}{{t}}{% endblocktranslate %}
        </p>
        <p class="h5">
            {% blocktranslate with c=obj.content|safe|capfirst|truncatechars:200 %}{{c}}{% endblocktranslate %}
        </p>
        <p class="txt-color h6">
            {% trans "On" %} {% blocktranslate with dt=obj.date|date %}{{dt}}{% endblocktranslate %} | {% trans "By" %} {{obj.publisher|capfirst}}
        </p>
        <div class="line"></div>
        <a href="{% url 'story:story-detail' obj.id %}" class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect mdl-color--purple-600 mdl-color-text--white text-uppercase">
            {% trans "Read More" %}
        </a>
    </div>
</div>
{% endif %}
{% endfor %}

{% endblock content %}

tips/templates/tips/tip_list.html
{% extends 'blog/base.html' %}
{% load static %}
{% load i18n %}
{% block content %}


<div class="container">
    <div class="my-2">
        <a href="{% url 'story:story-list' %}" class="mdl-color-text--purple">
            <!-- {% trans "Home" %} &gt; {% trans "Tips list" %}  -->
            <i class="material-icons" role="presentation">home</i>
            &gt; {% trans "Tips list" %} &gt;
        </a> 
    </div>
    <div class="line mb-3"></div>

    {% for obj in tip_data %}
        {% if obj.is_available == True %}
        <div class="col-md-12 mb-3">
            <a href="{% url 'tips:tip-detail' obj.id %}" class="txt-color h4">
                {% blocktranslate with t=obj.title|capfirst %}{{t}}{% endblocktranslate %}
            </a>
            <p class="h5">{% trans "On" %} {% blocktranslate with dt=obj.date|date %}{{dt}}{% endblocktranslate %} | {% trans "By" %} {{obj.author|capfirst}}</p>
        </div>

        <div class="line"></div>
        {% endif %}
    {% endfor %}

    
</div>

{% endblock %}

tips/templates/tips/tips_detail.html
{% extends 'blog/base.html' %}
{% load static %}
{% load crispy_forms_tags %} 
{% load i18n %}
{% block content %}

<div class="container">
    <div class="my-2">
        <a href="{% url 'tips:tip-list' %}" class="mdl-color-text--purple">
            <!-- {% trans "Back to list" %} &gt; {% trans "Details" %}  -->
            <i class="material-icons" role="presentation">list</i>
            &gt; {% trans "Details" %} &gt;
        </a>
    </div>
    <div class="line mb-3"></div>

    <div class="mdl-cell mdl-cell--10-col mdl-cell--12-col-tablet mdl-cell--12-col-phone mdl-shadow--2dp mx-auto">
        <div class="container p-4">
            <p class="txt-color h4">
                {% blocktranslate with t=ids.title|capfirst %}{{t}}{% endblocktranslate %}
            </p>
            <p class="lead">
                {% blocktranslate with c=ids.content|safe|capfirst|linebreaks %}{{c}}{% endblocktranslate %}
            </p>
            <p class="txt-color h5">
                {% trans "On" %} {% blocktranslate with dt=ids.date|date %}{{dt}}{% endblocktranslate %} | {% trans "By" %} {{ids.author|capfirst}}
            </p>
        </div>
    </div>

</div>


{% endblock %}